In [1]:
import numpy as np
import tensorflow
from tensorflow import keras
from keras import Sequential,layers
from keras.layers import Dense,Embedding,Flatten
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import one_hot

In [2]:
# data
mails = [
    
    'New offer, Its free',
    'Sale ! Sale ! Sale!',
    'New opportunity for you',
    'Bonus on your first purchase',
    'Apointment Letter',
    'College Notification',
    'Update your marks',
    'Free Travelling Offer',
    'Check your Profile',
    'Update Resume'
    
    
    
]

labels = np.array([0,0,0,0,1,1,1,0,1,1])

In [3]:
encode = [one_hot(i,50) for i in mails]

In [4]:
encode

[[10, 36, 18, 45],
 [1, 1, 1],
 [10, 32, 32, 29],
 [44, 47, 1, 31, 35],
 [6, 33],
 [15, 34],
 [35, 1, 27],
 [45, 41, 36],
 [48, 1, 35],
 [35, 9]]

In [5]:
max_seq = 5
pad_encode = pad_sequences(encode,max_seq,padding='post')
pad_encode

array([[10, 36, 18, 45,  0],
       [ 1,  1,  1,  0,  0],
       [10, 32, 32, 29,  0],
       [44, 47,  1, 31, 35],
       [ 6, 33,  0,  0,  0],
       [15, 34,  0,  0,  0],
       [35,  1, 27,  0,  0],
       [45, 41, 36,  0,  0],
       [48,  1, 35,  0,  0],
       [35,  9,  0,  0,  0]])

In [6]:
X = pad_encode
y = labels

In [7]:
X.shape,y.shape

((10, 5), (10,))

In [8]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(50,embeded_vector_size,input_length = max_seq, name = 'embedding' ))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [9]:
model.fit(X,y,epochs = 50)

Epoch 1/50
1/1 [==============================] - 11s 11s/step - loss: 0.7178 - accuracy: 0.2000
Epoch 2/50
1/1 [==============================] - 0s 2ms/step - loss: 0.7160 - accuracy: 0.2000
Epoch 3/50
1/1 [==============================] - 0s 2ms/step - loss: 0.7142 - accuracy: 0.2000
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 0.7124 - accuracy: 0.1000
Epoch 5/50
1/1 [==============================] - 0s 3ms/step - loss: 0.7106 - accuracy: 0.1000
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 0.7089 - accuracy: 0.2000
Epoch 7/50
1/1 [==============================] - 0s 2ms/step - loss: 0.7071 - accuracy: 0.2000
Epoch 8/50
1/1 [==============================] - 0s 2ms/step - loss: 0.7053 - accuracy: 0.2000
Epoch 9/50
1/1 [==============================] - 0s 2ms/step - loss: 0.7036 - accuracy: 0.2000
Epoch 10/50
1/1 [==============================] - 0s 2ms/step - loss: 0.7019 - accuracy: 0.3000
Epoch 11/50
1/1 [=====================

In [10]:
model.evaluate(X,y)

1/1 [==============================] - 0s 362ms/step - loss: 0.6285 - accuracy: 1.0000


[0.6284720301628113, 1.0]

In [11]:
input1 = ['offer free ','College Marks']

In [12]:
input_codes = [one_hot(i,50) for i in input1]
my_input = pad_sequences(input_codes,max_seq,padding='post')

In [13]:
model.predict(my_input)

array([[0.5075238 ],
       [0.52613837]], dtype=float32)

In [14]:
embedding_vectors = model.get_layer('embedding').get_weights()[0]

In [15]:
embedding_vectors[0]
# New offer, Its free

array([-0.03885119,  0.08304652, -0.0245782 , -0.00684798, -0.08055283],
      dtype=float32)

In [16]:
embedding_vectors[7]
# Free Travelling Offer
# Both mails are spams so they have nearly same embedding vectors

array([-0.03551457,  0.01908911, -0.02244775, -0.04487463, -0.04100984],
      dtype=float32)